name: AWS

on:
  push:
    branches:
      - production
      - staging
      - development

jobs:
  deploy:
    name: AWS Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Serverless Stage 
        run: echo "SERVERLESS_STAGE=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Serverless Deploy
        run: ../../node_modules/.bin/serverless deploy --stage $SERVERLESS_STAGE
        working-directory: ./packages/infra-sight-aws

      - name: Deploy API Metadata
        run: |
          echo \{\"name\":\"infra-sight\",\"version\":2,\"commit\":\"$GITHUB_SHA\"\} | aws s3 cp --content-type "application/json; charset=utf8" --cache-control "public, max-age=31536000" - s3://$(aws cloudformation describe-stack-resources --stack-name infra-sight-$SERVERLESS_STAGE | jq -r '.StackResources | map(select(.LogicalResourceId == "Bucket")) | .[0].PhysicalResourceId')/metadata.json
          aws cloudfront create-invalidation --distribution-id $(aws cloudformation describe-stack-resources --stack-name infra-sight-$SERVERLESS_STAGE | jq -r '.StackResources | map(select(.LogicalResourceId == "CloudFrontDistribution")) | .[0].PhysicalResourceId') --paths /
