name: AWS

on:
  push:
    branches:
      - production
      - staging
      - development

jobs:
  deploy:
    name: AWS Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        run: ../../node_modules/.bin/serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID  --secret $AWS_SECRET_ACCESS_KEY
        working-directory: ./packages/infra-sight-aws
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Serverless Deploy
        run: ../../node_modules/.bin/serverless deploy --stage ${GITHUB_REF##*/}
        working-directory: ./packages/infra-sight-aws
