name: NPM

on:
  push:
    branches:
      - production
      - staging
      - development

jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure NPM Credentials
        run: npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: NPM Pre-Publish Checks
        run: |
          node -p "'IS_SDK_PUBLISHED=' + $(npm view @infra-sight/sdk versions --json 2>/dev/null || echo "[]").includes(require('./packages/infra-sight-sdk/package.json').version)" >> $GITHUB_ENV

      - name: NPM Publish
        if: ${{ env.IS_SDK_PUBLISHED == 'false' }}
        run: npm --workspace=@infra-sight/sdk publish --access=public
